"""
Lightweight task orchestration service used by the WebSocket gateway.
Project Creator: Herman Swanepoel
"""

from __future__ import annotations

import asyncio
import textwrap
import time
from typing import Optional

from src.models.response import AgentResponse, Suggestion
from src.models.session import (
    AgentRunResult,
    TaskRequestPayload,
    TaskSessionResult,
    VerificationStatus,
    VerificationSummary,
)
from src.models.task import TaskType
from src.services.connection_manager import logger as ws_logger


class SimpleReasonerEngine:
    """Deterministic reasoning engine that generates structured agent responses."""

    AGENT_ID = "contextual_reasoner"
    AGENT_NAME = "Contextual Reasoner"

    async def generate(self, request: TaskRequestPayload) -> AgentResponse:
        """Generate a deterministic response for the incoming task request."""
        await asyncio.sleep(0)  # keep signature async friendly

        description = request.description.strip() or "General improvement"
        content = (request.content or "").strip()

        code_snippet = self._build_code_snippet(content, request.type)
        suggestion_description = self._build_description(description, request.type)
        confidence = self._determine_confidence(request.type, content)

        suggestion = Suggestion(
            id=f"{request.id}-suggestion",
            code=code_snippet,
            description=suggestion_description,
            confidence=confidence,
        )

        reasoning = textwrap.dedent(
            f"""
            Primary objective: {description}
            Suggested adjustment focuses on readability and maintainability while keeping the
            original intent intact. Confidence is derived from static analysis heuristics that
            inspect the supplied code and task type.
            """
        ).strip()

        return AgentResponse(
            agent_id=self.AGENT_ID,
            agent_name=self.AGENT_NAME,
            suggestions=[suggestion],
            confidence=0.68 if confidence.value == "medium" else 0.82,
            reasoning=reasoning,
            metadata={
                "task_type": request.type.value,
                "uses_context": bool(request.context and request.context.metadata),
                "content_present": bool(content),
            },
        )

    def _build_code_snippet(self, content: str, task_type: TaskType) -> str:
        if content:
            annotated = textwrap.indent(content, "    ")
            return textwrap.dedent(
                f"""
                # Suggested revision generated by Contextual Reasoner
                {task_type.value} = (
{annotated}
                )
                """
            ).strip()

        template = "# TODO: Provide implementation for the requested task\n"
        return template + f"# Task type: {task_type.value}\n"

    def _build_description(self, description: str, task_type: TaskType) -> str:
        return f"Addressing '{description}' for task type '{task_type.value}'."

    def _determine_confidence(self, task_type: TaskType, content: str):
        from src.models.response import ConfidenceLevel

        if not content:
            return ConfidenceLevel.LOW
        if task_type in {TaskType.TEST_GENERATION, TaskType.BUG_FIX}:
            return ConfidenceLevel.MEDIUM
        return ConfidenceLevel.HIGH


class SimpleVerifierEngine:
    """Basic verification pass that validates the reasoner output."""

    async def verify(
        self, request: TaskRequestPayload, response: AgentResponse
    ) -> VerificationSummary:
        await asyncio.sleep(0)

        has_code = any(suggestion.code for suggestion in response.suggestions)
        status = VerificationStatus.PASSED if has_code else VerificationStatus.SKIPPED
        confidence = 0.55 if status == VerificationStatus.PASSED else 0.0

        metadata = {
            "evaluated_agent": response.agent_id,
            "suggestion_count": len(response.suggestions),
            "task_type": request.type.value,
        }

        return VerificationSummary(status=status, confidence=confidence, metadata=metadata)


class TaskOrchestrator:
    """Coordinates task execution across the lightweight reasoning and verification stages."""

    def __init__(
        self,
        reasoner: Optional[SimpleReasonerEngine] = None,
        verifier: Optional[SimpleVerifierEngine] = None,
    ):
        self._reasoner = reasoner or SimpleReasonerEngine()
        self._verifier = verifier or SimpleVerifierEngine()

    async def execute(self, request: TaskRequestPayload) -> TaskSessionResult:
        """Process a task request and return an aggregated session result."""
        start_time = time.perf_counter()

        ws_logger.info(
            "orchestrator_task_received",
            extra={
                "task_id": request.id,
                "task_type": request.type.value,
                "has_content": bool(request.content),
            },
        )

        agent_response = await self._reasoner.generate(request)

        verification_summary = None
        if self._verifier:
            verification_summary = await self._verifier.verify(request, agent_response)

        duration_ms = (time.perf_counter() - start_time) * 1000
        summary = self._build_summary(agent_response, verification_summary)

        result = TaskSessionResult(
            task_id=request.id,
            status="completed",
            summary=summary,
            responses=[
                AgentRunResult(
                    response=agent_response,
                    duration_ms=duration_ms,
                    escalated=verification_summary is not None,
                )
            ],
            verification=verification_summary,
            metrics={
                "duration_ms": round(duration_ms, 2),
                "suggestion_count": len(agent_response.suggestions),
            },
        )

        ws_logger.info(
            "orchestrator_task_completed",
            extra={
                "task_id": request.id,
                "duration_ms": result.metrics["duration_ms"],
                "verification_status": (
                    verification_summary.status.value
                    if verification_summary
                    else VerificationStatus.SKIPPED.value
                ),
            },
        )

        return result

    def _build_summary(
        self,
        agent_response: AgentResponse,
        verification_summary: Optional[VerificationSummary],
    ) -> str:
        primary_suggestion = agent_response.suggestions[0] if agent_response.suggestions else None
        verification_text = "Verification skipped."
        if verification_summary:
            verification_text = (
                f"Verification {verification_summary.status.value}"
                f" (confidence {verification_summary.confidence:.2f})."
            )

        if primary_suggestion:
            return (
                f"Generated suggestion from {agent_response.agent_name}: "
                f"{primary_suggestion.description}. {verification_text}"
            )

        return (
            "No actionable suggestions were produced by the orchestrator. " f"{verification_text}"
        )


__all__ = ["TaskOrchestrator", "SimpleReasonerEngine", "SimpleVerifierEngine"]
